
Vagrant.configure("2") do |config|
  
  #config.vm.box = "ubuntu/precise64"
  config.vm.box = "ubuntu/trusty64"
  #config.vm.network "private_network", ip: "10.0.1.50"
  config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end


  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
      #mgmt_config.vm.box = "ubuntu/precise64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.90"
  #    mgmt_config.vm.synced_folder "../data", "/vagrant_data"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
 #     mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  # create load balancer
  config.vm.define :lb do |lb_config|
      #lb_config.vm.box = "ubuntu/precise64"
      lb_config.vm.hostname = "lb"
      lb_config.vm.network :private_network, ip: "10.0.15.91"
      lb_config.vm.network "forwarded_port", guest: 80, host: 8080
      lb_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
  end

  # create some web servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..2).each do |i|
    config.vm.define "web#{i}" do |node|
        #node.vm.box = "ubuntu/precise64"
        node.vm.hostname = "web#{i}"
        node.vm.network :private_network, ip: "10.0.15.10#{i}"
        node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
    end
  end
end
